// <auto-generated />
namespace Project4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Changerequirementsofdesignerinclothes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changerequirementsofdesignerinclothes));
        
        string IMigrationMetadata.Id
        {
            get { return "201605310125528_Change requirements of designer in clothes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
